# https://taskfile.dev

version: '3'

vars:
  version: "1.0"
  docname: Exam
  file: main
  builddir: build

tasks:
  default:
    deps: [mkdirs, doc, docsol]
  copy_src:
    cmds:
      - cp {{.file}}.typ {{.builddir}}/
      - cp {{.file}}.typ {{.builddir}}/{{.file}}_sol.typ
      - sed "s/#(cfg.sol = false)/#(cfg.sol = true)/" --in-place {{.builddir}}/{{.file}}_sol.typ
      - cp tutor.toml {{.builddir}}/
      - cp -r src {{.builddir}}/src
  doc:
    cmds:
      - cd {{.builddir}} && typst compile {{.file}}.typ {{.docname}}.{{.version}}.pdf
    deps: [copy_src]
  docsol:
    cmds: 
      - cd {{.builddir}} && typst compile {{.file}}_sol.typ {{.docname}}_solution.{{.version}}.pdf
    deps: [copy_src]
  mkdirs:
    cmds:
      - mkdir -p {{.builddir}}
  clean:
    cmds:
      - rm -r {{.builddir}}
  watch:
    cmds:
      - typst watch {{.file}}.typ {{.builddir}}/{{.docname}}.pdf
  open:
    cmds:
      - xdg-open {{.builddir}}/{{.docname}}.{{.version}}.pdf
  img:
    cmds:
      - inkscape -o {{.builddir}}/example_question_mode.svg {{.builddir}}/{{.docname}}.{{.version}}.pdf
      - inkscape -o {{.builddir}}/example_solution_mode.svg {{.builddir}}/{{.docname}}.{{.version}}.pdf
      - cp {{.builddir}}/example_question_mode.svg ../imgs/
      - cp {{.builddir}}/example_solution_mode.svg ../imgs/
