# https://taskfile.dev

version: '3'

vars:
  version: "1.0"
  docname: Exam
  file: main
  builddir: build

tasks:
  default:
    cmds:
      - go-task --list
  all:
    desc: Compile document in question and solution mode.
    deps: [doc, docsol]
  mkdirs:
    cmds:
      - mkdir -p {{.builddir}}
  clean:
    desc: Remove all generated files.
    cmds:
      - rm -r {{.builddir}}
  doc:
    desc: Compile document in question mode.
    cmds:
      - typst compile --input tutor_sol=false {{.file}}.typ {{.builddir}}/{{.docname}}.{{.version}}.pdf
    deps: [mkdirs]
  docsol:
    desc: Compile document in solution mode.
    cmds: 
      - typst compile --input tutor_sol=true {{.file}}.typ  {{.builddir}}/{{.docname}}_solution.{{.version}}.pdf
    deps: [mkdirs]
  watch:
    desc: Watch document in question mode.
    cmds:
      - typst watch --input tutor_sol=false {{.file}}.typ {{.builddir}}/{{.docname}}.{{.version}}.pdf
    deps: [mkdirs]
  watchsol:
    desc: Watch document in solution mode.
    cmds:
      - typst watch --input tutor_sol=true {{.file}}.typ {{.builddir}}/{{.docname}}_solution.{{.version}}.pdf
    deps: [mkdirs]
  open:
    desc: Open document in question mode.
    cmds:
      - xdg-open {{.builddir}}/{{.docname}}.{{.version}}.pdf
  opensol:
    desc: Open document in solution mode.
    cmds:
      - xdg-open {{.builddir}}/{{.docname}}_solution.{{.version}}.pdf
  img:
    cmds:
      - inkscape -o {{.builddir}}/example_question_mode.svg {{.builddir}}/{{.docname}}.{{.version}}.pdf
      - inkscape -o {{.builddir}}/example_solution_mode.svg {{.builddir}}/{{.docname}}_solution.{{.version}}.pdf
      - cp {{.builddir}}/example_question_mode.svg ../imgs/
      - cp {{.builddir}}/example_solution_mode.svg ../imgs/
